In [1]:
!pip install numpy

  Using cached numpy-2.2.6-cp312-cp312-win_amd64.whl.metadata (60 kB)
Using cached numpy-2.2.6-cp312-cp312-win_amd64.whl (12.6 MB)


In [2]:
import numpy as np

## create arrays 
## create 1 d array 
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [3]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [8]:
arr2 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(arr2)
arr2.shape

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


(2, 6)

In [10]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
#### numpy vectorized operations
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

In [14]:
##element wise addition
print(arr1+arr2)

[11 22 33 44 55]


In [15]:
##element wwise substraction
print(arr1-arr2)

[ -9 -18 -27 -36 -45]


In [16]:
##element wise multiplication
print(arr1*arr2)

[ 10  40  90 160 250]


In [18]:
##element wise division 
print(arr2/arr1)

[10. 10. 10. 10. 10.]


In [20]:
##universal function
arr = np.array([1,2,3,4,5,6])

In [21]:
##sqrt 
print(np.sqrt(arr))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]


In [22]:
##exponential
print(np.exp(arr))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]


In [23]:
## sine
print(np.sin(arr))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]


In [24]:
##natural log
print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [26]:
##array slicing and indexing
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [28]:
arr[0][0]

np.int64(1)

In [30]:
arr[1:,2:]

array([[6],
       [9]])

In [33]:
arr[0:2,2:]

array([[3],
       [6]])

In [35]:
arr[1:,1:2]

array([[5],
       [8]])

In [36]:
###modify array elements
arr[0,0]=1000
print(arr)

[[1000    2    3]
 [   4    5    6]
 [   7    8    9]]


In [ ]:
##stastical concept
##normalization --- to have mean of 0 and standard deviation of 1
data = np.array([1,2,3,5,6,10,34,42,53])

##mean and SD
mean = np.mean(data)
sd = np.std(data)

# normalize tha data 
normalized_data = (data-mean)/sd
print("normalized data = ",normalized_data)

normalized data =  [-0.86620581 -0.8131728  -0.76013979 -0.65407377 -0.60104076 -0.38890873
  0.88388348  1.30814755  1.89151064]


In [44]:
## logical operation
data = np.array([1,2,3,4,5,6,7,8,9,10])
data>5
data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])